services:
  experiment-rf:
    build: &experiment_build
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.12
    volumes: &volumes
      - ./data:/data
    hostname: rf
    environment:
      DATA_OWNER: &owner 1000:1000
      MAX_SAMPLES: 50_0000 
      N_JOBS: 1  
      MODEL_RandomForest: |
          sklearn.ensemble.RandomForestClassifier:
              n_estimators: [10, 50, 100]
              max_depth: [null, 10, 20]

  experiment-mlp:
    build: *experiment_build
    volumes: *volumes
    hostname: mlp
    environment:
      DATA_OWNER: *owner
      MAX_SAMPLES: 50_0000  
      N_JOBS: 1  
      MODEL_MLP: |
          sklearn.neural_network.MLPClassifier:
              hidden_layer_sizes:
                - [50]
                - [100,]
                - [50, 50]
              activation: ['tanh', 'relu']
              solver: ['adam', 'sgd']